# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish to Github packages.

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for cert installation
      run: chmod +x installCerts.sh
    - name: Install certs
      run: bash installCerts.sh
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to Github packages
      run: ./gradlew publish
      env:
        USERNAME: 'EATSTEAK'
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
